# ~/.config/starship.toml
[shell]
disabled = true

[[battery.display]]
threshold = 30
style = "bold red"

[character]
error_symbol = " (bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "[git:$branch]($style) "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold black "
tag_symbol = "commit:"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "CONFLICT!"
ahead = "ahead:×${count} "
behind = "behind:×${count} "
diverged = "ahead:×${ahead_count} & behind:×${behind_count} "
untracked = "added:×${count} "
stashed = "stash:x${count} "
modified = "upd:×${count} "
staged = "staged:×${count} "
renamed = "mv:×${count} "
deleted = "del:×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = true 
format = "host:$hostname ($style)"
trim_at = "-"
style = "bold blue"
disabled = false

[memory_usage]
format = "memory:[${ram}( | ${swap})]($style) "
threshold = 70 
style = "bold dimmed white"
disabled = true

[package]
disabled = false

[docker_context]
format = "[docker:$context$version]($style) "

[nodejs]
disabled = true
format = "[node:$version]($style) "

[ruby]
disabled = true
format = "[ruby:$version]($style) "

[terraform]
format = "[terraform:$workspace]($style) "

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = true 

[username]
style_user = "bold blue"
show_always = true
