# ~/.config/starship.toml
[shell]
disabled = true

[[battery.display]]
threshold = 30
style = "bold red"

[character]
error_symbol = " (bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = " "
style = "bold italic yellow"

[git_commit]
commit_hash_length = 8
style = "bold italic black "
tag_symbol = "  "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = " "
ahead = " ×${count} "
behind = " ×${count} "
diverged = " ×${ahead_count}  ×${behind_count} "
untracked = " ×${count} "
stashed = " x${count} "
modified = " ×${count} "
staged = " ×${count} "
renamed = " ×${count} "
deleted = " ×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = true 
format = "  $hostname ($style)"
trim_at = "-"
style = "bold blue"
disabled = false

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70 
style = "bold dimmed white"
disabled = true

[package]
disabled = false

[docker_context]
format = "[$symbol$context$version]($style) "
symbol = " "

[nodejs]
format = "[$symbol$version]($style) "
symbol = " "

[ruby]
format = "[$symbol$version]($style) "
symbol = " "

[terraform]
format = "[$symbol$workspace]($style) "
symbol = "TF"

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = true 

[username]
style_user = "bold blue"
show_always = true
