# ~/.config/starship.toml

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$buf\
$c\
$cmake\
$cobol\
$container\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$fill\
$jobs\
$battery\
$time\
$status\
$cmd_duration\
$line_break\
$shell\
$character"""

continuation_prompt = "[>>](bold yellow)"

[fill]
symbol = "-"
style = "cyan"

[shell]
disabled = true

[[battery.display]]
threshold = 30
style = "bold red"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "[git:$branch]($style) "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold yellow "
tag_symbol = "commit:"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "CONFLICT!"
ahead = "↥:${count} "
behind = "↧:${count} "
diverged = "↥/↧:${ahead_count}/${behind_count} "
untracked = "U:${count} "
stashed = "*:${count} "
modified = "M:${count} "
staged = "A:${count} "
renamed = "R:${count} "
deleted = "D:${count} "
style = "bright-white"
format = "$ahead_behind$all_status"

[hostname]
ssh_only = true 
format = "host:$hostname ($style)"
trim_at = "-"
style = "bold blue"
disabled = false

[memory_usage]
format = "memory:[${ram}( | ${swap})]($style) "
threshold = 70 
style = "bold dimmed white"
disabled = true

[package]
disabled = false

[docker_context]
format = "[docker:$context$version]($style) "

[nodejs]
disabled = true
format = "[node:$version]($style) "

[ruby]
disabled = true
format = "[ruby:$version]($style) "

[terraform]
format = "[terraform:$workspace]($style) "

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = true 

[username]
style_user = "bold blue"
show_always = true
